// Common source countries for tourists visiting Pakistan. Sorted alphabetically.
// Extend as needed.
export const COUNTRIES = [
  "Australia",
  "Austria",
  "Bahrain",
  "Bangladesh",
  "Belgium",
  "Brazil",
  "Canada",
  "China",
  "Czech Republic",
  "Denmark",
  "Egypt",
  "Finland",
  "France",
  "Germany",
  "Greece",
  "Hungary",
  "India",
  "Indonesia",
  "Iran",
  "Ireland",
  "Israel",
  "Italy",
  "Japan",
  "Jordan",
  "Kazakhstan",
  "Kuwait",
  "Kyrgyzstan",
  "Malaysia",
  "Mexico",
  "Nepal",
  "Netherlands",
  "New Zealand",
  "Norway",
  "Oman",
  "Philippines",
  "Poland",
  "Portugal",
  "Qatar",
  "Romania",
  "Russia",
  "Saudi Arabia",
  "Singapore",
  "South Africa",
  "South Korea",
  "Spain",
  "Sri Lanka",
  "Sweden",
  "Switzerland",
  "Thailand",
  "Turkey",
  "Ukraine",
  "United Arab Emirates",
  "United Kingdom",
  "United States",
  "Uzbekistan",
  "Vietnam",
] as const;

export const NATIONALITIES = [
  "Australian",
  "Austrian",
  "Bahraini",
  "Bangladeshi",
  "Belgian",
  "Brazilian",
  "British",
  "Canadian",
  "Chinese",
  "Czech",
  "Danish",
  "Dutch",
  "Egyptian",
  "Emirati",
  "Finnish",
  "French",
  "German",
  "Greek",
  "Hungarian",
  "Indian",
  "Indonesian",
  "Iranian",
  "Irish",
  "Israeli",
  "Italian",
  "Japanese",
  "Jordanian",
  "Kazakh",
  "Kuwaiti",
  "Kyrgyz",
  "Malaysian",
  "Mexican",
  "Nepali",
  "New Zealander",
  "Norwegian",
  "Omani",
  "Filipino",
  "Polish",
  "Portuguese",
  "Qatari",
  "Romanian",
  "Russian",
  "Saudi",
  "Singaporean",
  "South African",
  "South Korean",
  "Spanish",
  "Sri Lankan",
  "Swedish",
  "Swiss",
  "Thai",
  "Turkish",
  "Ukrainian",
  "American",
  "Uzbek",
  "Vietnamese",
] as const;
