import {
  Mountains,
  Flower,
  CastleTurret,
  SunHorizon,
  Handshake,
  Boat,
  Sun,
  Leaf,
  PawPrint,
  MaskHappy,
  Confetti,
  Mosque,
  Plant,
  Tent,
  Car,
  Sparkle,
  Wind,
  TreeEvergreen,
  Campfire,
  Drop,
  Diamond,
  Horse,
  Bank,
  Waves,
  House,
  UmbrellaSimple,
  Fire,
  Anchor,
  Fish,
  Snowflake,
  Eye,
  EyeSlash,
  Lock,
  Backpack,
  Heart,
  Gear,
  ListChecks,
  Calendar,
  CalendarCheck,
  User,
  Users,
  GlobeHemisphereWest,
  Check,
  CreditCard,
  ArrowRight,
  ArrowLeft,
  CaretDown,
  CaretUp,
  CaretLeft,
  CaretRight,
  MagnifyingGlass,
  Compass,
  Binoculars,
  Path,
  MapPin,
  Star,
  ShieldCheck,
  X,
  ChatCircle,
  Phone,
  Envelope,
  WhatsappLogo,
  Moon,
  FacebookLogo,
  InstagramLogo,
  YoutubeLogo,
  Bookmark,
  PencilSimple,
} from "@phosphor-icons/react/dist/ssr";
import type { Icon as PhosphorIcon } from "@phosphor-icons/react";

export const iconMap = {
  mountains: Mountains,
  flower: Flower,
  castle: CastleTurret,
  boat: Boat,
  "sun-horizon": SunHorizon,
  handshake: Handshake,
  sun: Sun,
  leaf: Leaf,
  "paw-print": PawPrint,
  "mask-happy": MaskHappy,
  confetti: Confetti,
  mosque: Mosque,
  plant: Plant,
  tent: Tent,
  car: Car,
  sparkle: Sparkle,
  wind: Wind,
  "tree-evergreen": TreeEvergreen,
  campfire: Campfire,
  drop: Drop,
  diamond: Diamond,
  horse: Horse,
  bank: Bank,
  waves: Waves,
  house: House,
  "umbrella-simple": UmbrellaSimple,
  fire: Fire,
  anchor: Anchor,
  fish: Fish,
  snowflake: Snowflake,
  eye: Eye,
  "eye-slash": EyeSlash,
  lock: Lock,
  backpack: Backpack,
  heart: Heart,
  gear: Gear,
  "list-checks": ListChecks,
  calendar: Calendar,
  "calendar-check": CalendarCheck,
  user: User,
  users: Users,
  globe: GlobeHemisphereWest,
  check: Check,
  "credit-card": CreditCard,
  "arrow-right": ArrowRight,
  "arrow-left": ArrowLeft,
  "caret-down": CaretDown,
  "caret-up": CaretUp,
  "caret-left": CaretLeft,
  "caret-right": CaretRight,
  search: MagnifyingGlass,
  compass: Compass,
  binoculars: Binoculars,
  path: Path,
  "map-pin": MapPin,
  star: Star,
  "shield-check": ShieldCheck,
  x: X,
  "chat-circle": ChatCircle,
  phone: Phone,
  envelope: Envelope,
  whatsapp: WhatsappLogo,
  moon: Moon,
  facebook: FacebookLogo,
  instagram: InstagramLogo,
  youtube: YoutubeLogo,
  bookmark: Bookmark,
  edit: PencilSimple,
} satisfies Record<string, PhosphorIcon>;

export type IconName = keyof typeof iconMap;

export const iconSizeMap = {
  xs: 12,
  sm: 14,
  md: 16,
  lg: 20,
  xl: 24,
  "2xl": 28,
  "3xl": 32,
} as const;

export type IconSize = keyof typeof iconSizeMap;
